### ISSUE TITLE
Mongodb

### ISSUE THREAD

**Issue by lucianosekulic** [ULL-ESIT-INF-DSI-2021/ull-esit-inf-dsi-20-21-prct11-menu-api-grupo-r#1]
Intento utilizar la base de datos de mongodb y sigo las intrucciones de los apuntes, sin embargo me sale que el servicio no esta cargado, que no encuentra el servicio, etc. Lo dejo adjunto en la siguiente imagen, no sabría cual puede ser el error. 

![image](https://user-images.githubusercontent.com/72558007/119162944-d9420800-ba52-11eb-8963-71c9c7bffceb.png)

**Comment by esegredo** [comment]
Hola @lucianosekulic , buenas tardes.

No pasa nada. Es que, simplemente, no está ejecutándose. Continua con el tutorial.

Saludos.
Eduardo
